import { _electron as electron } from 'playwright-core';
import fs from 'node:fs/promises';
import path from 'node:path';
import assert from 'node:assert/strict';
import { createRequire } from 'node:module';
import { mixedFixtures } from '../tests/fixtures.ts';
import { Media } from '../electron/media.ts';
const require=createRequire(import.meta.url);
const packaged=process.env.FIELD_KIT_EXECUTABLE;
const root=path.resolve('.test-output',`ui-${packaged?'packaged':'development'}-${Date.now()}`),sources=path.join(root,'source fixtures 雨'),library=path.join(root,'My field library'),profile=path.join(root,'profile');
await fs.mkdir(sources,{recursive:true});await fs.mkdir(library,{recursive:true});
await mixedFixtures(sources,new Media(path.resolve('vendor/ffmpeg/bin')));
let app,page;const errors=[],blocked=[];const metrics={root,packaged:!!packaged,executable:packaged||'development',checks:[]};
const start=async()=>{
  app=await electron.launch({executablePath:packaged||require('electron'),args:[...(packaged?[]:['.']),`--user-data-dir=${profile}`],env:packaged?{...process.env,PATH:'C:\\Windows\\System32;C:\\Windows'}:process.env,timeout:45000});
  page=await app.firstWindow();page.setDefaultTimeout(15000);page.on('pageerror',e=>errors.push(e.message));page.on('request',r=>{if(/^https?:/.test(r.url()))blocked.push(r.url());});
  await page.waitForLoadState('domcontentloaded');await page.context().setOffline(true);metrics.version=await app.evaluate(({app})=>app.getVersion());
};
const dialog=async paths=>app.evaluate(({dialog},paths)=>{dialog.showOpenDialog=async()=>({canceled:false,filePaths:paths});},paths);
try{
  await start();await page.getByRole('button',{name:'Create a library',exact:true}).waitFor();await page.screenshot({path:path.join(root,'01-welcome.png')});
  await page.getByRole('button',{name:'About',exact:true}).click();const about=page.getByRole('dialog',{name:'About Field Kit',exact:true});await about.getByText(`Field Kit ${metrics.version}`,{exact:true}).waitFor();await page.screenshot({path:path.join(root,'01b-about.png')});await about.getByRole('button',{name:'Copy diagnostics',exact:true}).click();await about.getByRole('button',{name:'Copied',exact:true}).waitFor();await about.getByRole('button',{name:'Close',exact:true}).click();metrics.checks.push('visible version and copyable local diagnostics');
  const security=await app.evaluate(({BrowserWindow})=>{const p=BrowserWindow.getAllWindows()[0].webContents.getLastWebPreferences();return {sandbox:p.sandbox,contextIsolation:p.contextIsolation,nodeIntegration:p.nodeIntegration,webSecurity:p.webSecurity};});
  assert.deepEqual(security,{sandbox:true,contextIsolation:true,nodeIntegration:false,webSecurity:true});
  assert.equal(await page.evaluate(()=>typeof window.require),'undefined');metrics.security=security;metrics.checks.push('sandbox and bridge');
  await dialog([library]);await page.getByRole('button',{name:'Create a library',exact:true}).click();await page.getByRole('heading',{name:'All materials',exact:true}).waitFor();
  await page.getByRole('button',{name:'New collection',exact:true}).click();await page.getByRole('textbox',{name:'Collection name'}).fill('Forest walk');await page.getByRole('button',{name:'Create collection',exact:true}).click();
  await dialog([sources]);await page.getByRole('button',{name:'Import folder',exact:true}).click();await page.getByRole('dialog',{name:'Import report'}).waitFor();await page.getByRole('button',{name:'Done',exact:true}).click();
  const state=await page.evaluate(()=>window.fieldKit.getState());assert.equal(state.assets.length,9);assert.equal(state.collections[0].name,'Forest walk');metrics.checks.push('native folder selection bridge; mixed import report');
  await page.evaluate(()=>{const input=document.createElement('input');input.type='file';input.id='verification-drop-input';input.hidden=true;document.body.append(input);});
  await page.locator('#verification-drop-input').setInputFiles(path.join(sources,'moss & stone.png'));
  const dropped=await page.evaluateHandle(()=>{const transfer=new DataTransfer();transfer.items.add(document.querySelector('#verification-drop-input').files[0]);return transfer;});
  await page.dispatchEvent('.app','drop',{dataTransfer:dropped});await page.getByText('0 imported · 1 duplicates skipped',{exact:true}).waitFor();await dropped.dispose();await page.locator('#verification-drop-input').evaluate(e=>e.remove());metrics.checks.push('file-backed drag and drop through preload');
  const image=state.assets.find(a=>a.kind==='image'&&a.info.format==='png'),sound=state.assets.find(a=>a.name==='Footsteps 雨');
  await page.getByRole('button',{name:`Edit ${image.name}`,exact:true}).click();await page.getByAltText('Processed square texture').waitFor();
  await page.getByRole('button',{name:'Crop',exact:true}).click();const cropBox=await page.locator('.crop-frame').boundingBox();await page.mouse.move(cropBox.x+cropBox.width*.1,cropBox.y+cropBox.height*.1);await page.mouse.down();await page.mouse.move(cropBox.x+cropBox.width*.85,cropBox.y+cropBox.height*.9,{steps:5});await page.mouse.up();await page.getByText('Saved · preview is export-ready',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Square crop',exact:true}).click();await page.getByRole('button',{name:'0°',exact:true}).click();await page.getByRole('button',{name:'Flip H',exact:true}).click();metrics.checks.push('pointer crop, square preset, rotation and flip');
  await page.getByLabel('Texture export size').selectOption('512');
  await page.getByLabel('Blend edges',{exact:true}).fill('0.7');await page.getByLabel('Brightness',{exact:true}).fill('1.15');await page.getByRole('button',{name:'Tiled',exact:true}).click();
  await page.getByText('Saved · preview is export-ready',{exact:true}).waitFor();await page.screenshot({path:path.join(root,'02-texture.png')});metrics.checks.push('image processing with sharp in worker; tiled preview; auto-save');
  await page.getByRole('button',{name:'Undo',exact:true}).click();await page.getByRole('button',{name:'Redo',exact:true}).click();
  await page.getByRole('tab',{name:'Details',exact:true}).click();await page.getByLabel('Material name',{exact:true}).fill('Rain wall');await page.getByLabel('Tags',{exact:false}).fill('wall, weathered');await page.getByLabel('Private notes').fill('Private UI verification note');await page.getByRole('button',{name:'Save details',exact:true}).click();await page.getByText('Details saved',{exact:true}).waitFor();
  await page.getByRole('button',{name:`Edit ${sound.name}`,exact:true}).click();await page.locator('audio[aria-label="Processed sound preview"]').waitFor();
  const handle=page.getByRole('slider',{name:'Trim start handle',exact:true});await handle.scrollIntoViewIfNeeded();const trimBox=await page.locator('.trim-wave').boundingBox();await handle.hover();await page.mouse.down();await page.mouse.move(trimBox.x+trimBox.width*.1,trimBox.y+trimBox.height/2,{steps:5});await page.mouse.up();assert(Number(await page.getByLabel('Trim start seconds').inputValue())>0);metrics.checks.push('pointer trim handle');
  await page.getByLabel('Trim start seconds').fill('0.25');await page.getByLabel('Trim end seconds').fill('3.75');await page.getByLabel('Fade in (seconds)',{exact:true}).fill('0.12');await page.getByLabel('Fade out (seconds)',{exact:true}).fill('0.15');await page.getByLabel('Normalize peak to −1 dBFS',{exact:true}).check();await page.getByLabel('Sound output channels').selectOption('1');await page.getByLabel('Boundary crossfade',{exact:true}).fill('0.15');
  await page.getByText('Saved · preview is export-ready',{exact:true}).waitFor();
  await page.getByRole('button',{name:'Audition boundary ↻',exact:true}).click();
  await page.waitForFunction(()=>{const a=document.querySelector('audio');return a&&!a.paused&&a.currentTime>0&&a.currentTime<1&&a.readyState>=2;});
  const playback=await page.locator('audio').evaluate(a=>({duration:a.duration,currentTime:a.currentTime,readyState:a.readyState,loop:a.loop,paused:a.paused}));assert(Math.abs(playback.duration-3.35)<.01);metrics.playback=playback;
  await page.screenshot({path:path.join(root,'03-sound.png')});metrics.checks.push('audio trim, fades, normalization, crossfade, mono and playback timeline');
  await page.getByRole('tab',{name:'Try in a scene',exact:true}).click();await page.locator('.scene-canvas canvas, .scene-fallback').waitFor();assert.equal(await page.locator('.scene-material strong').textContent(),'Rain wall');
  assert(await page.locator('.editor audio').evaluate(a=>a.paused));await page.locator('audio[aria-label="Scene sound preview"]').evaluate(a=>a.play());await page.waitForFunction(()=>document.querySelector('audio[aria-label="Scene sound preview"]').currentTime>.1);await page.locator('audio[aria-label="Scene sound preview"]').evaluate(a=>a.pause());metrics.checks.push('scene audio audition; hidden workbench player pauses');
  metrics.webgl=await page.locator('.scene-canvas canvas').count()>0;await page.getByRole('button',{name:'Sphere',exact:true}).click();await page.getByLabel('Scene texture repeat').fill('3');await page.screenshot({path:path.join(root,'04-scene.png')});
  if(metrics.webgl){await page.locator('.scene-canvas canvas').focus();await page.keyboard.press('ArrowLeft');await page.keyboard.press('ArrowUp');}await page.getByRole('button',{name:'Reset camera',exact:true}).click();metrics.checks.push('scene geometry, repeats, reset and keyboard orbit');
  if(metrics.webgl){await page.locator('.scene-canvas canvas').evaluate(canvas=>canvas.dispatchEvent(new Event('webglcontextlost',{cancelable:true})));await page.locator('.scene-fallback').waitFor();await page.screenshot({path:path.join(root,'04b-fallback.png')});metrics.checks.push('forced WebGL context loss and usable 2D fallback');}
  await page.keyboard.press('Control+f');assert.equal(await page.getByRole('textbox',{name:'Search assets'}).evaluate(e=>document.activeElement===e),true);await page.getByRole('textbox',{name:'Search assets'}).fill('weathered');assert((await page.locator('.asset-card').count())>=1);await page.getByRole('textbox',{name:'Search assets'}).fill('');await page.keyboard.press('Tab');assert(await page.evaluate(()=>document.activeElement?.tagName==='BUTTON'));metrics.checks.push('keyboard search and focus navigation');
  const output=path.join(root,'UI pack.zip');await app.evaluate(({dialog},output)=>{dialog.showSaveDialog=async()=>({canceled:false,filePath:output});},output);
  await page.getByRole('button',{name:'Export pack',exact:true}).click();await page.getByRole('button',{name:'Choose destination',exact:true}).click();await page.getByText(/Exported 2 assets to/).waitFor();await fs.access(output);metrics.checks.push('export through rendered UI');
  await app.close();await fs.rename(sources,path.join(root,'External sources moved'));await start();await page.getByRole('button',{name:'Edit Rain wall',exact:true}).waitFor();const reopened=await page.evaluate(()=>window.fieldKit.getState());assert.equal(reopened.assets.find(a=>a.id===image.id).notes,'Private UI verification note');assert.equal(reopened.assets.find(a=>a.id===sound.id).recipe.crossfade,.15);metrics.checks.push('application restart persistence and moved external sources');
  await page.getByRole('button',{name:'Edit Rain wall',exact:true}).click();await page.getByAltText('Processed square texture').waitFor();
  await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].setSize(1100,760);BrowserWindow.getAllWindows()[0].webContents.setZoomFactor(1.1);});
  await page.waitForTimeout(300);
  await page.screenshot({path:path.join(root,'05-laptop-scaling.png')});
  await page.getByRole('button',{name:'Field notes',exact:true}).click();const notes=page.getByRole('dialog',{name:'Field notes',exact:true});assert.equal(await notes.locator('details').count(),9);await page.screenshot({path:path.join(root,'05b-field-notes.png')});await notes.getByRole('button',{name:'Back to work',exact:true}).click();metrics.checks.push('scannable Field Notes sections');
  const overflow=await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth);assert.equal(overflow,false);metrics.checks.push('1100x760 laptop window at 110% zoom');
  await app.evaluate(({BrowserWindow})=>{BrowserWindow.getAllWindows()[0].setSize(1280,800);BrowserWindow.getAllWindows()[0].webContents.setZoomFactor(1.25);});await page.waitForTimeout(300);await page.screenshot({path:path.join(root,'06-scaling-125.png')});assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>window.innerWidth),false);const layout125=await page.getByRole('button',{name:'Export pack',exact:true}).evaluate(e=>({right:e.getBoundingClientRect().right,width:window.innerWidth,height:window.innerHeight,dpr:window.devicePixelRatio}));assert(layout125.right<=layout125.width,JSON.stringify(layout125));metrics.layout125=layout125;metrics.checks.push('1280x800 window at 125% zoom');
  await page.context().setOffline(true);await page.getByRole('button',{name:`Edit ${sound.name}`,exact:true}).click();await page.locator('audio').waitFor();await page.getByLabel('Volume',{exact:true}).fill('0.8');await page.getByText('Saved · preview is export-ready',{exact:true}).waitFor();metrics.checks.push('offline processed audio regeneration');
  const forbidden=await page.evaluate(async()=>{try{await window.fieldKit.render('../bad',{});return false;}catch{return true;}});assert(forbidden);metrics.checks.push('invalid IPC payload rejected');
  assert.equal(errors.length,0,errors.join('\n'));assert.equal(blocked.length,0);metrics.rendererErrors=errors;metrics.networkRequests=blocked;metrics.finished=new Date().toISOString();
  await fs.writeFile(path.join(root,'results.json'),JSON.stringify(metrics,null,2));console.log('UI_RESULTS '+JSON.stringify(metrics));
}finally{if(app)await app.close().catch(()=>{});}
