import { useEffect, useRef, useState } from 'react';
import { Check, Crop, FlipHorizontal2, FlipVertical2, Grid2X2, LoaderCircle, Redo2, RotateCcw, RotateCw, Undo2 } from 'lucide-react';
import { audioRecipeSchema, defaultAudio, defaultImage, imageRecipeSchema, mediaUrl, type Asset, type AudioRecipe, type ImageRecipe, type RenderResult } from './shared';
import { recipeSaves } from './recipe-saves';
import { PresetBar, type PresetProps } from './presets';

type Props = PresetProps & { asset: Asset; onSaved: (a: Asset) => void; onRendered: (a: Asset, result: RenderResult) => void; onPending: (v: boolean) => void; onInvalid: (v: boolean) => void };
function useRecipe<T extends ImageRecipe | AudioRecipe>({ asset, onSaved, onRendered, onPending, onInvalid }: Props) {
  const [history, setHistory] = useState<{ past: T[]; present: T; future: T[]; touched: boolean }>({ past: [], present: structuredClone(recipeSaves.recipe(asset) as T), future: [], touched: false });
  const [result, setResult] = useState<RenderResult | null>(null), [status, setStatus] = useState('Preparing preview…'), [error, setError] = useState('');
  const [retry, setRetry] = useState(0);
  const recipe = history.present;
  const change = (value: T) => setHistory(h => JSON.stringify(value) === JSON.stringify(h.present) ? h : { past: [...h.past, h.present].slice(-80), present: value, future: [], touched: true });
  const undo = () => setHistory(h => h.past.length ? { past: h.past.slice(0, -1), present: h.past.at(-1)!, future: [h.present, ...h.future], touched: true } : h);
  const redo = () => setHistory(h => h.future.length ? { past: [...h.past, h.present], present: h.future[0], future: h.future.slice(1), touched: true } : h);
  useEffect(() => {
    const keyboard = (event: KeyboardEvent) => {
      const target = event.target as HTMLElement;
      if (!(event.ctrlKey || event.metaKey) || target.closest('dialog, input:not([type=range]), textarea, [contenteditable=true], [role=tabpanel][hidden]')) return;
      if (!document.querySelector('.editor')?.checkVisibility()) return;
      if (event.key.toLowerCase() === 'z') { event.preventDefault(); event.shiftKey ? redo() : undo(); }
      if (event.key.toLowerCase() === 'y') { event.preventDefault(); redo(); }
    };
    window.addEventListener('keydown', keyboard); return () => window.removeEventListener('keydown', keyboard);
  }, []);
  useEffect(() => {
    let alive = true;
    const parsed = (asset.kind === 'image' ? imageRecipeSchema : audioRecipeSchema).safeParse(recipe);
    onInvalid(!parsed.success);
    if (!parsed.success) { setError(parsed.error.issues[0].message); setStatus('Review the fields below'); onPending(true); return () => { onPending(false); onInvalid(false); }; }
    setError(''); setStatus('Rendering preview…'); onPending(true);
    // Saving is immediate; preview rendering is debounced. Switching assets cannot discard a valid edit.
    const edited = history.touched || recipeSaves.has(asset.id);
    const save = edited ? recipeSaves.save(asset, recipe, onSaved) : Promise.resolve(asset);
    save.catch(e => { if (alive) { setError(e.message); setStatus('Could not save'); } });
    const timer = window.setTimeout(async () => {
      try { const saved = await save; if (!alive) return; const rendered = await window.fieldKit.render(asset.id, recipe); if (alive) { setResult(rendered); setStatus(edited || asset.prepared ? 'Saved · preview is export-ready' : 'Original · change a control to prepare'); onRendered(saved, rendered); onPending(false); } }
      catch (e) { if (alive) { const message = (e as Error).message.replace(/^Error invoking remote method '[^']+': Error: /, ''); if (message !== 'Cancelled') setError(message); setStatus('Preview unavailable'); onPending(false); } }
    }, 300);
    return () => { alive = false; clearTimeout(timer); onPending(false); };
  }, [recipe, retry]);
  return { recipe, change, undo, redo, canUndo: !!history.past.length, canRedo: !!history.future.length, result, status, error, retry: () => setRetry(v => v + 1) };
}
function Slider({ label, value, min = 0, max = 2, step = .01, onChange, display }: { label: string; value: number; min?: number; max?: number; step?: number; onChange: (v: number) => void; display?: string }) {
  return <label className="slider-field"><span>{label}<output>{display ?? `${Math.round(value * 100)}%`}</output></span><input type="range" min={min} max={max} step={step} value={value} aria-label={label} onChange={e => onChange(Number(e.target.value))}/></label>;
}
function HistoryBar({ state, reset }: { state: { undo: () => void; redo: () => void; canUndo: boolean; canRedo: boolean }; reset: () => void }) { return <div className="history-bar"><button className="icon" onClick={state.undo} disabled={!state.canUndo} aria-label="Undo"><Undo2 size={17}/></button><button className="icon" onClick={state.redo} disabled={!state.canRedo} aria-label="Redo"><Redo2 size={17}/></button><button className="text-button reset" onClick={reset}><RotateCcw size={14}/> Reset to original</button></div>; }
function RecipeStatus({ status, error, retry }: { status: string; error: string; retry: () => void }) { return <div className={`recipe-status ${error ? 'invalid' : ''}`} role="status">{error ? <><span>{error}</span><button className="text-button" onClick={retry}>Retry preview</button></> : <>{status.startsWith('Rendering') || status.startsWith('Preparing') ? <LoaderCircle size={13} className="spin"/> : <Check size={13}/>} {status}</>}</div>; }
export function ImageEditor(props: Props) {
  const state = useRecipe<ImageRecipe>(props), { recipe: r, change, result } = state;
  const [view, setView] = useState<'single' | 'tiled' | 'crop' | 'compare'>('single'), [repeat, setRepeat] = useState(3);
  const set = (patch: Partial<ImageRecipe>) => change({ ...r, ...patch });
  const width = props.asset.info.width!, height = props.asset.info.height!;
  const square = () => { const side = Math.min(r.crop.w * width, r.crop.h * height); const w = side / width, h = side / height; set({ crop: { x: r.crop.x + (r.crop.w - w) / 2, y: r.crop.y + (r.crop.h - h) / 2, w, h } }); setView('crop'); };
  return <div className="editor"><div className="preview-toolbar"><div className="segmented"><button className={view === 'single' ? 'chosen' : ''} onClick={() => setView('single')}>Texture</button><button className={view === 'tiled' ? 'chosen' : ''} onClick={() => setView('tiled')}><Grid2X2 size={13}/> Tiled</button><button aria-pressed={view === 'compare'} className={view === 'compare' ? 'chosen' : ''} onClick={() => setView('compare')}>Compare</button><button className={view === 'crop' ? 'chosen' : ''} onClick={() => setView('crop')}><Crop size={13}/> Crop</button></div>{view === 'tiled' && <label className="repeat-label">Repeat<select aria-label="Tile repeat" value={repeat} onChange={e => setRepeat(Number(e.target.value))}>{[2,3,4,6].map(n => <option key={n}>{n}</option>)}</select></label>}</div>
    {view === 'compare' ? <div className="texture-comparison"><figure><figcaption>Before · full original</figcaption><img alt="Original photograph before edits" src={mediaUrl(props.asset.original)}/></figure><figure><figcaption>After · export texture</figcaption>{result ? <img alt="Texture after edits" src={mediaUrl(result.path)}/> : <LoaderCircle className="spin"/>}</figure><p>Compare framing, orientation and color. The original keeps its full proportions; the exported texture is square.</p></div> : view === 'crop' ? <div className="crop-stage"><div className="crop-frame" style={{ aspectRatio: `${width}/${height}`, maxWidth: `${Math.min(460, 300 * width / height)}px` }} onPointerDown={e => { if (e.button !== 0) return; const rect = e.currentTarget.getBoundingClientRect(), startX = Math.max(0, Math.min(.99, (e.clientX - rect.left) / rect.width)), startY = Math.max(0, Math.min(.99, (e.clientY - rect.top) / rect.height)); e.currentTarget.setPointerCapture(e.pointerId); const el = e.currentTarget; const move = (event: PointerEvent) => { const endX = Math.max(0, Math.min(1, (event.clientX - rect.left) / rect.width)), endY = Math.max(0, Math.min(1, (event.clientY - rect.top) / rect.height)); const x = Math.min(startX, endX), y = Math.min(startY, endY); change({ ...r, crop: { x, y, w: Math.max(.01, Math.abs(endX - startX)), h: Math.max(.01, Math.abs(endY - startY)) } }); }; const up = () => { el.removeEventListener('pointermove', move); el.removeEventListener('pointerup', up); el.removeEventListener('pointercancel', up); }; el.addEventListener('pointermove', move); el.addEventListener('pointerup', up); el.addEventListener('pointercancel', up); }}><img src={mediaUrl(props.asset.original)} alt="Upright original; drag to crop" draggable={false}/><div className="crop-box" style={{ left: `${r.crop.x * 100}%`, top: `${r.crop.y * 100}%`, width: `${r.crop.w * 100}%`, height: `${r.crop.h * 100}%` }}><span/><span/></div></div><small>Drag a region, or use the precise fields below.</small></div> : <div className={`texture-stage ${view}`} style={view === 'tiled' && result ? { backgroundImage: `url("${mediaUrl(result.path)}")`, backgroundSize: `${100 / repeat}% auto` } : undefined}>{view === 'single' && result && <img alt="Processed square texture" src={mediaUrl(result.path)}/>} {!result && <LoaderCircle className="spin" size={24}/>}</div>}
    <RecipeStatus status={state.status} error={state.error} retry={state.retry}/><HistoryBar state={state} reset={() => change(structuredClone(defaultImage))}/>
    <PresetBar {...props} kind="image" recipe={r} change={change}/><div className="control-section"><div className="section-heading"><h3>Frame & orientation</h3><button className="text-button" onClick={square}><Crop size={14}/> Square crop</button></div><div className="orientation"><button onClick={() => set({ rotation: ((r.rotation + 90) % 360) as ImageRecipe['rotation'] })}><RotateCw size={15}/> {r.rotation}°</button><button aria-pressed={r.flipX} onClick={() => set({ flipX: !r.flipX })}><FlipHorizontal2 size={16}/> Flip H</button><button aria-pressed={r.flipY} onClick={() => set({ flipY: !r.flipY })}><FlipVertical2 size={16}/> Flip V</button></div>
      {view === 'crop' && <div className="crop-fields">{(['x','y','w','h'] as const).map((key, i) => <label key={key}>{['Left %','Top %','Width %','Height %'][i]}<input type="number" min={i < 2 ? 0 : 1} max={100} step="0.1" value={Number((r.crop[key] * 100).toFixed(1))} onChange={e => { const v = Math.max(i < 2 ? 0 : .01, Math.min(1, Number(e.target.value) / 100)); let crop = { ...r.crop, [key]: v }; if (key === 'x') crop.x = Math.min(v, 1 - crop.w); if (key === 'y') crop.y = Math.min(v, 1 - crop.h); if (key === 'w') crop.w = Math.min(v, 1 - crop.x); if (key === 'h') crop.h = Math.min(v, 1 - crop.y); set({ crop }); }}/></label>)}</div>}
    </div><div className="control-section"><h3>Light & color</h3><div className="control-columns"><Slider label="Brightness" value={r.brightness} min={.2} onChange={v => set({ brightness: v })}/><Slider label="Contrast" value={r.contrast} min={.2} onChange={v => set({ contrast: v })}/><Slider label="Saturation" value={r.saturation} onChange={v => set({ saturation: v })}/></div></div>
    <div className="control-section"><h3>Make it repeat</h3><Slider label="Blend edges" max={1} value={r.blend} onChange={v => set({ blend: v })}/><p className="control-help">An aid to reducing seams, applied to the exported pixels. Check the tiled view; results depend on your photograph.</p></div>
    <div className="output-section"><div><h3>Texture output</h3><p>Square PNG · sRGB · color only</p></div><select aria-label="Texture export size" value={r.size} onChange={e => set({ size: Number(e.target.value) as ImageRecipe['size'] })}>{[512,1024,2048].map(n => <option key={n} value={n}>{n} × {n}</option>)}</select></div>{result?.info.enlarged && <p className="warning-note">This output enlarges the cropped source. A smaller export may look sharper.</p>}
  </div>;
}
export function Waveform({ values }: { values: number[] }) {
  const points = values.length ? values : [0];
  const top = points.map((v, i) => `${(i / (points.length - 1 || 1) * 600).toFixed(1)},${(50 - Math.max(.007, v) * 45).toFixed(1)}`).join(' ');
  const bottom = [...points].reverse().map((v, i) => `${((points.length - 1 - i) / (points.length - 1 || 1) * 600).toFixed(1)},${(50 + Math.max(.007, v) * 45).toFixed(1)}`).join(' ');
  return <svg viewBox="0 0 600 100" preserveAspectRatio="none" className="waveform" role="img" aria-label="Waveform from decoded audio samples"><line x1="0" y1="50" x2="600" y2="50"/><polygon points={`${top} ${bottom}`}/></svg>;
}
export function SoundEditor(props: Props) {
  const state = useRecipe<AudioRecipe>(props), { recipe: r, change, result } = state;
  const [loop, setLoop] = useState(false), [playhead, setPlayhead] = useState(0);
  const player = useRef<HTMLAudioElement>(null), trim = useRef<HTMLDivElement>(null);
  const set = (patch: Partial<AudioRecipe>) => change({ ...r, ...patch });
  const duration = props.asset.info.duration!;
  const drag = (edge: 'start' | 'end', event: React.PointerEvent<HTMLButtonElement>) => {
    event.preventDefault(); const el = event.currentTarget; el.setPointerCapture(event.pointerId); const rect = trim.current!.getBoundingClientRect();
    const move = (e: PointerEvent) => { const time = Math.round(Math.min(duration, Math.max(0, (e.clientX - rect.left) / rect.width * duration)) * 1000) / 1000; const start = edge === 'start' ? Math.min(time, r.end - .02) : r.start, end = edge === 'end' ? Math.max(time, r.start + .02) : r.end, len = end - start; change({ ...r, start, end, fadeIn: Math.min(r.fadeIn, len / 2), fadeOut: Math.min(r.fadeOut, len / 2), crossfade: Math.min(r.crossfade, len / 3) }); };
    const up = () => { el.removeEventListener('pointermove', move); el.removeEventListener('pointerup', up); el.removeEventListener('pointercancel', up); };
    el.addEventListener('pointermove', move); el.addEventListener('pointerup', up); el.addEventListener('pointercancel', up);
  };
  return <div className="editor sound-editor"><div className="wave-heading"><span className="eyebrow">ORIGINAL RECORDING</span><span>{duration.toFixed(3)}s</span></div><div className="trim-wave" ref={trim}><Waveform values={result?.originalWaveform || props.asset.waveform}/><div className="trim-shade" style={{ left: 0, width: `${r.start / duration * 100}%` }}/><div className="trim-shade" style={{ right: 0, width: `${(1 - r.end / duration) * 100}%` }}/><div className="trim-selection" style={{ left: `${r.start / duration * 100}%`, width: `${(r.end - r.start) / duration * 100}%` }}/>{(['start','end'] as const).map(edge => <button key={edge} role="slider" aria-label={`Trim ${edge} handle`} aria-valuemin={0} aria-valuemax={duration} aria-valuenow={r[edge]} className="trim-handle" style={{ left: `${r[edge] / duration * 100}%` }} onPointerDown={e => drag(edge, e)} onKeyDown={e => { if (e.key === 'ArrowLeft' || e.key === 'ArrowRight') { e.preventDefault(); const v = r[edge] + (e.key === 'ArrowRight' ? .01 : -.01); set({ [edge]: Math.max(edge === 'end' ? r.start + .02 : 0, Math.min(edge === 'start' ? r.end - .02 : duration, v)) }); } }}><span/></button>)}</div><div className="wave-time"><span>0:00</span><span>Drag the handles to trim</span><span>{duration.toFixed(2)}s</span></div>
    <div className="trim-fields"><label>Start (seconds)<input type="number" aria-label="Trim start seconds" min={0} max={duration} step="0.001" value={r.start} onChange={e => set({ start: Number(e.target.value) })}/></label><label>End (seconds)<input type="number" aria-label="Trim end seconds" min={.02} max={duration} step="0.001" value={r.end} onChange={e => set({ end: Number(e.target.value) })}/></label></div>
    <RecipeStatus status={state.status} error={state.error} retry={state.retry}/><HistoryBar state={state} reset={() => change(defaultAudio(duration))}/>
    <PresetBar {...props} kind="audio" recipe={r} change={change}/><div className="processed-sound"><div className="section-heading"><h3>Processed preview</h3><label className="check-label"><input type="checkbox" checked={loop} onChange={e => setLoop(e.target.checked)}/> Loop</label></div>{result ? <><div className="rendered-wave" onClick={e => { if (player.current) { const rect = e.currentTarget.getBoundingClientRect(); player.current.currentTime = Math.max(0, Math.min(result.info.duration!, (e.clientX - rect.left) / rect.width * result.info.duration!)); } }}><Waveform values={result.waveform || []}/><div className="playhead" style={{ left: `${playhead / (result.info.duration || 1) * 100}%` }}/></div><audio ref={player} controls preload="metadata" loop={loop} src={mediaUrl(result.path)} onTimeUpdate={() => setPlayhead(player.current?.currentTime || 0)} aria-label="Processed sound preview"/><div className="audio-preview-actions"><span>{result.info.duration?.toFixed(3)}s · {result.info.peakDb?.toFixed(1)} dBFS peak</span><button className="text-button" onClick={() => { const p = player.current; if (p) { setLoop(true); p.loop = true; p.currentTime = Math.max(0, result.info.duration! - 1); void p.play().catch(() => {}); } }}>Audition boundary ↻</button></div></> : <p className="muted">Your processed recording will appear here.</p>}</div>
    <div className="control-section"><h3>Level & fades</h3><Slider label="Volume" max={3} value={r.volume} onChange={v => set({ volume: v })}/><div className="control-columns"><label>Fade in (seconds)<input type="number" min={0} max={30} step="0.01" value={r.fadeIn} onChange={e => set({ fadeIn: Number(e.target.value) })}/></label><label>Fade out (seconds)<input type="number" min={0} max={30} step="0.01" value={r.fadeOut} onChange={e => set({ fadeOut: Number(e.target.value) })}/></label></div><label className="check-label normalize"><input type="checkbox" checked={r.normalize} onChange={e => set({ normalize: e.target.checked })}/> Normalize peak to −1 dBFS</label><p className="control-help">Normalization sets the final peak after volume, fades and crossfade.</p></div>
    <div className="control-section"><h3>Loop boundary</h3><Slider label="Boundary crossfade" value={r.crossfade} max={Math.min(10, (r.end - r.start) / 3)} step={.01} display={`${r.crossfade.toFixed(2)}s`} onChange={v => set({ crossfade: v })}/><p className="control-help">Overlaps the tail and head. Shortens the result by the crossfade time. Enable Loop, then audition the boundary.</p></div><div className="output-section"><div><h3>Sound output</h3><p>WAV · 48 kHz · 16-bit PCM</p></div><select aria-label="Sound output channels" value={r.channels} onChange={e => set({ channels: Number(e.target.value) as 1 | 2 })}><option value={1}>Mono</option><option value={2}>Stereo</option></select></div>
  </div>;
}
